[package]
name = "minhypr"
version = "0.1.0"
edition = "2021"
description = "A window minimization manager for Hyprland"
authors = ["Otavio Soares <tavinq@hotmail.com>"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"